### ISSUE TITLE
Can the Font-Family be customized per element?

### ISSUE THREAD

**Issue by mikebronner** [tailwindcss/typography#15]
Often-times site designs utilize a different font-family for the headings than in the body. Is there a way to customize this? I checked the default settings as per the readme, but didn't see any indication of being able to do that in the default styles. Thanks!

**Comment by wikipeter** [comment]
Hi @mikebronner check my [last](https://github.com/tailwindcss/typography/issues/14#issuecomment-658261095) comment on #14 

Cheers

**Comment by mikebronner** [comment]
@wikipeter Awesome! I will give that a shot. :)

**Comment by adamwathan** [comment]
Yep just write the CSS rules you need in your config:

```js
module.exports = {
  theme: {
    typography: {
      default: {
        css: {
          h1: {
            fontFamily: 'Comic Sans',
          },
          blockquote: {
            fontFamily: 'Wingdings',
          },
        }
      }
    }
  }
}
```

**Comment by bitmanic** [comment]
I'm having trouble getting this to work well with the `theme` helper.

Given the following config:
```js
module.exports = {
  theme: {
    fontFamily: {
      sans: ['museo', 'sans-serif'],
    },
    typography: (theme) => ({
      default: {
        css: {
          h1: {
            fontFamily: theme('fontFamily.sans'),
          },
        },
      },
    }),
  }, 
}
```

I expect the generated CSS to look like this:
```css
.prose h1 {
  font-family: museo, sans-serif;
}
```

The actual generated CSS looks like this:
```css
.prose h1 {
  font-family: museo;
  font-family: sans-serif;
}
```

The issue is that browsers will use the last declared font-family, which is actually the least desired fallback font within a font stack. Am I missing something here, or is this a genuine issue?

**Comment by adamwathan** [comment]
Use theme('fontFamily.sans').join(', ') 👍🏻
