### ISSUE TITLE
Overriding default colours inline

### ISSUE THREAD

**Issue by belafonte** [tailwindcss/typography#26]
Hello hello,

I really like the approach of this plugin and would like to use it.
But when I tried it out, I ran into problems with custom colours and overriding attributes.

Overriding colours in HTML is not possible. I think that is by design ?
Overriding the defaults does not help unfortunately.
From my experience, especially header (`<h1>`) do often have a custom Colors depending on the current topic.
E.g. Lettuce (green), Tomato (red), Orange (orange) should have their heading in the corresponding color.

In general it is not possible to override specific attributes in HTML, for instance margins or as said colours.
Probably because the plugin is loaded last?

Sorry I hope I don't miss something obvious here, that would make this possible using tailwind...
But I couldn't find something in the docs beside overriding defaults etc. in tailwind config.

Thank you!

**Comment by adamwathan** [comment]
Hey! The underlying issue here is just CSS specificity.

Our rules look like this:

```css
.prose h1 {
  color: #000;
}
```

This rule has a specificity of 011 (one class and one element).

Our utilities like `text-green-500` have a specificity of 010, so even though they are defined later in the stylesheet, the prose styles defeat them.

Your best bet if you need utilities to override prose styles is to enable the `important` option in Tailwind:

https://tailwindcss.com/docs/configuration/#important

This is perfectly reasonable and not an anti-pattern or anything, utilities in Bootstrap are `!important` by default for example 👍

**Comment by royvanv** [comment]
You could add a class to your `.prose` element and use the following CSS.

```
.prose.lettuce h1 {
    color: green;
}
```
